// features.go defines the ordered feature name schemas for Netflow and PCAP
// XGBoost models. These slices map feature indices (f0..fN) to human-readable
// names used in explainability output and ML vector construction.
package engine

var FeatureNames = []string{
	"flow_count",
	"unique_dst_ips",
	"unique_dst_ports",
	"total_bytes",
	"total_packets",
	"avg_bytes_per_flow",
	"avg_packets_per_flow",
	"pct_tcp",
	"pct_udp",
	"pct_icmp",
	"pct_well_known_ports",
	"pct_high_ports",
	"avg_duration",
	"iat_mean",
	"iat_variance",
	"port_symmetry",
	"ip_port_ratio",
	"avg_payload_per_packet",
	"pct_syn_only",
	"pct_rst",
	"iat_cv",
}

var PcapFeatureNames = []string{
	"Header_Length",
	"Time_To_Live",
	"Rate",
	"fin_flag_number",
	"syn_flag_number",
	"rst_flag_number",
	"psh_flag_number",
	"ack_flag_number",
	"ece_flag_number",
	"cwr_flag_number",
	"syn_count",
	"ack_count",
	"fin_count",
	"rst_count",
	"IGMP",
	"HTTPS",
	"HTTP",
	"Telnet",
	"DNS",
	"SMTP",
	"SSH",
	"IRC",
	"TCP",
	"UDP",
	"DHCP",
	"ARP",
	"ICMP",
	"IPv",
	"LLC",
	"Tot sum",
	"Min",
	"Max",
	"AVG",
	"Std",
	"Tot size",
	"IAT",
	"Number",
	"Variance",
	"Protocol Type",
}
