// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD2b7633eDecodeGoversionModels(in *jlexer.Lexer, out *NetflowRecord) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "first":
			if in.IsNull() {
				in.Skip()
			} else {
				out.First = string(in.String())
			}
		case "last":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Last = string(in.String())
			}
		case "in_packets":
			if in.IsNull() {
				in.Skip()
			} else {
				out.InPackets = int64(in.Int64())
			}
		case "in_bytes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.InBytes = int64(in.Int64())
			}
		case "proto":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Proto = int(in.Int())
			}
		case "tcp_flags":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TCPFlags = string(in.String())
			}
		case "src_port":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SrcPort = int(in.Int())
			}
		case "dst_port":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DstPort = int(in.Int())
			}
		case "src4_addr":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Src4Addr = string(in.String())
			}
		case "dst4_addr":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Dst4Addr = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGoversionModels(out *jwriter.Writer, in NetflowRecord) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"first\":"
		out.RawString(prefix[1:])
		out.String(string(in.First))
	}
	{
		const prefix string = ",\"last\":"
		out.RawString(prefix)
		out.String(string(in.Last))
	}
	{
		const prefix string = ",\"in_packets\":"
		out.RawString(prefix)
		out.Int64(int64(in.InPackets))
	}
	{
		const prefix string = ",\"in_bytes\":"
		out.RawString(prefix)
		out.Int64(int64(in.InBytes))
	}
	{
		const prefix string = ",\"proto\":"
		out.RawString(prefix)
		out.Int(int(in.Proto))
	}
	{
		const prefix string = ",\"tcp_flags\":"
		out.RawString(prefix)
		out.String(string(in.TCPFlags))
	}
	{
		const prefix string = ",\"src_port\":"
		out.RawString(prefix)
		out.Int(int(in.SrcPort))
	}
	{
		const prefix string = ",\"dst_port\":"
		out.RawString(prefix)
		out.Int(int(in.DstPort))
	}
	{
		const prefix string = ",\"src4_addr\":"
		out.RawString(prefix)
		out.String(string(in.Src4Addr))
	}
	{
		const prefix string = ",\"dst4_addr\":"
		out.RawString(prefix)
		out.String(string(in.Dst4Addr))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NetflowRecord) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGoversionModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NetflowRecord) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGoversionModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NetflowRecord) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGoversionModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NetflowRecord) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGoversionModels(l, v)
}
func easyjsonD2b7633eDecodeGoversionModels1(in *jlexer.Lexer, out *MLResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "IP":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IP = string(in.String())
			}
		case "Probability":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Probability = float64(in.Float64())
			}
		case "IsBotnet":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsBotnet = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGoversionModels1(out *jwriter.Writer, in MLResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"IP\":"
		out.RawString(prefix[1:])
		out.String(string(in.IP))
	}
	{
		const prefix string = ",\"Probability\":"
		out.RawString(prefix)
		out.Float64(float64(in.Probability))
	}
	{
		const prefix string = ",\"IsBotnet\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsBotnet))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MLResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGoversionModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MLResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGoversionModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MLResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGoversionModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MLResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGoversionModels1(l, v)
}
